# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := false
TARGET_CPU_VARIANT :=cortex-a9

# Kernel
TARGET_PREBUILT_KERNEL := device/TOLINO/ntx_6sl/kernel
BOARD_KERNEL_CMDLINE := console=ttymxc0,115200 init=/init androidboot.console=ttymxc0 video=mxcepdcfb:E060SCM,bpp=16 video=mxc_elcdif_fb:off no_console_suspend
BOARD_KERNEL_BASE := 0x80800000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_SEPARATED_DT := false
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 6258688
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 402644992
BOARD_CACHEIMAGE_PARTITION_SIZE := 402644992
BOARD_USERDATAIMAGE_PARTITION_SIZE := 536862720
# BOARD_KERNEL_PAGESIZE * 64
BOARD_FLASH_BLOCK_SIZE := 131072

# Storage
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_FSTAB := device/TOLINO/ntx_6sl/recovery.fstab

# Screen
TW_DEFAULT_BRIGHTNESS := 50
TW_MAX_BRIGHTNESS := 100
#TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_TIMEOUT := true
TW_NO_SCREEN_BLANK := true

RECOVERY_TOUCHSCREEN_FLIP_X := true
RECOVERY_TOUCHSCREEN_SWAP_XY := true

#IMX EPDC
TW_TARGET_USES_IMX_EPDC := true
TW_SCREEN_ROTATION_IMX := 3

#MISC
TW_NO_REBOOT_BOOTLOADER := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_DEFAULT_USB_INIT := true

#THEME
TW_THEME := portrait_hdpi
TW_CUSTOM_THEME := $(if (test -d "theme"),device/TOLINO/ntx_6sl/theme,)
